# Generated by Django 4.2.4 on 2023-09-20 07:49

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('file', models.FileField(upload_to=api.models.Document.upload_path)),
                ('name', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
